# Generated by Django 5.0.6 on 2024-06-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='troopattributes',
            name='untrained_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='troopattributes',
            name='untrained_name',
            field=models.CharField(default='Untrained Unit', max_length=50),
        ),
        migrations.AddField(
            model_name='troopattributes',
            name='untrained_power',
            field=models.IntegerField(default=0),
        ),
    ]
