# Generated by Django 5.0.6 on 2024-07-27 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_account', '0004_alter_userprofile_faction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diplomacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('relation', models.CharField(choices=[('Ally', 'Ally'), ('Neutral', 'Neutral'), ('Enemy', 'Enemy')], max_length=20)),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_diplomacy', to='user_account.userprofile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_diplomacy', to='user_account.userprofile')),
            ],
        ),
    ]
