# Generated by Django 5.0.6 on 2024-07-31 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomacy', '0002_alter_diplomacy_relation'),
        ('user_account', '0004_alter_userprofile_faction'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonAggression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('target_accepted', models.BooleanField(default=False)),
                ('user_accepted', models.BooleanField(default=False)),
                ('length', models.IntegerField(default=1440)),
                ('expired', models.BooleanField(default=False)),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_non_agg', to='user_account.userprofile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_non_agg', to='user_account.userprofile')),
            ],
        ),
    ]
