# Generated by Django 5.0.6 on 2024-07-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomacy', '0004_diplomatictimeline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diplomatictimeline',
            name='event',
        ),
        migrations.AddField(
            model_name='diplomatictimeline',
            name='event_message_target',
            field=models.CharField(choices=[('You attacked', 'You attacked'), ('They attacked you', 'They attacked you'), ('You proposed an alliance', 'You proposed an alliance'), ('They proposed an alliance', 'They proposed an alliance'), ('You accepted an alliance proposal', 'You accepted an alliance proposal'), ('They accepted an alliance proposal', 'They accepted an alliance proposal'), ('You proposed a Non-Aggression Pact', 'You proposed a Non-Aggression Pact'), ('They proposed a Non-Aggression Pact', 'They proposed a Non-Aggression Pact'), ('You accepted a Non-Aggression Pact proposal', 'You accepted a Non-Aggression Pact proposal'), ('They accepted a Non-Aggression Pact proposal', 'They accepted a Non-Aggression Pact proposal'), ('You declared war', 'You declared war'), ('They declared war', 'They declared war'), ('Your Non-Aggression Pact expired', 'Your Non-Aggression Pact expired'), ('You ended your alliance', 'You ended your alliance'), ('They ended your alliance', 'They ended your alliance'), ('You set your relations to neutral', 'You set your relations to neutral'), ('They set your relations to neutral', 'They set your relations to neutral')], default=-2024, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diplomatictimeline',
            name='event_message_user',
            field=models.CharField(choices=[('You attacked', 'You attacked'), ('They attacked you', 'They attacked you'), ('You proposed an alliance', 'You proposed an alliance'), ('They proposed an alliance', 'They proposed an alliance'), ('You accepted an alliance proposal', 'You accepted an alliance proposal'), ('They accepted an alliance proposal', 'They accepted an alliance proposal'), ('You proposed a Non-Aggression Pact', 'You proposed a Non-Aggression Pact'), ('They proposed a Non-Aggression Pact', 'They proposed a Non-Aggression Pact'), ('You accepted a Non-Aggression Pact proposal', 'You accepted a Non-Aggression Pact proposal'), ('They accepted a Non-Aggression Pact proposal', 'They accepted a Non-Aggression Pact proposal'), ('You declared war', 'You declared war'), ('They declared war', 'They declared war'), ('Your Non-Aggression Pact expired', 'Your Non-Aggression Pact expired'), ('You ended your alliance', 'You ended your alliance'), ('They ended your alliance', 'They ended your alliance'), ('You set your relations to neutral', 'You set your relations to neutral'), ('They set your relations to neutral', 'They set your relations to neutral')], default='You proposed a Non-Aggression Pact', max_length=500),
            preserve_default=False,
        ),
    ]
