from django.contrib import admin


from .models import IntelLog, AttackLog


class IntelLogAdmin(admin.ModelAdmin):    
    fields = (
        'report_id',
        'date',
        'result', 
        'defender_user_profile', 
        'defender_intel',
        'defender_troops', 
        'defender_technologies', 
        'defender_bonus',
        'attacker_user_profile', 
        'attacker_intel', 
        'attacker_troops',
        'attacker_technologies',
        'attacker_bonus',
        'attacker_weak_intel_troops_loss', 
        'attacker_strong_intel_troops_loss', 
        'attacker_elite_intel_troops_loss',
        'defender_defence_power', 
        'defender_attack_power',
        'defender_intel_power', 
        'defender_income_power',  
        'defender_weak_attack_troops', 
        'defender_strong_attack_troops',  
        'defender_elite_attack_troops',  
        'defender_weak_defence_troops',  
        'defender_strong_defence_troops', 
        'defender_elite_defence_troops',  
        'defender_weak_intel_troops',  
        'defender_strong_intel_troops',  
        'defender_elite_intel_troops',  
        'defender_income_specialists',  
        'defender_untrained_units',
        )
        
    list_display = (
        'report_id',
        'date',
        'result', 
        'defender_user_profile', 
        'defender_intel',
        'defender_troops', 
        'defender_technologies', 
        'defender_bonus',
        'attacker_user_profile', 
        'attacker_intel', 
        'attacker_troops',
        'attacker_technologies',
        'attacker_bonus',
        'attacker_weak_intel_troops_loss', 
        'attacker_strong_intel_troops_loss', 
        'attacker_elite_intel_troops_loss',
        'defender_defence_power', 
        'defender_attack_power',
        'defender_intel_power', 
        'defender_income_power',  
        'defender_weak_attack_troops', 
        'defender_strong_attack_troops',  
        'defender_elite_attack_troops',  
        'defender_weak_defence_troops',  
        'defender_strong_defence_troops', 
        'defender_elite_defence_troops',  
        'defender_weak_intel_troops',  
        'defender_strong_intel_troops',  
        'defender_elite_intel_troops',  
        'defender_income_specialists',  
        'defender_untrained_units',  
        )
admin.site.register(IntelLog, IntelLogAdmin)

class AttackLogAdmin(admin.ModelAdmin):    
    fields = (
    'report_id', 
    'date', 
    'result',
    'defender_user_profile',                                    
    'attacker_user_profile',
    'attacker_t1_loss',
    'attacker_t2_loss',
    'attacker_t3_loss',
    'defender_t1_loss',
    'defender_t2_loss',
    'defender_t3_loss',
    'attacker_t1_count',
    'attacker_t2_count',
    'attacker_t3_count',
    'defender_t1_count',
    'defender_t2_count',
    'defender_t3_count',
    'attacker_attack_snap',
    'defender_defence_snap',
    'data_crystal_gain',
        )
        
    list_display = (
        'report_id', 
    'date', 
    'result',
    'defender_user_profile',                                    
    'attacker_user_profile',
    'attacker_t1_loss',
    'attacker_t2_loss',
    'attacker_t3_loss',
    'defender_t1_loss',
    'defender_t2_loss',
    'defender_t3_loss',
    'attacker_t1_count',
    'attacker_t2_count',
    'attacker_t3_count',
    'defender_t1_count',
    'defender_t2_count',
    'defender_t3_count',
    'attacker_attack_snap',
    'defender_defence_snap',
    'data_crystal_gain',  
        )
admin.site.register(AttackLog, AttackLogAdmin)

