# Generated by Django 5.0.6 on 2024-06-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='data_crystal_balance',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='production',
            name='income',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='production',
            name='knowledge_points',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='production',
            name='pop_growth',
            field=models.IntegerField(default=10),
        ),
    ]
