# Generated by Django 5.0.6 on 2024-07-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_production_knowledge_points_growth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='knowledge_points_growth',
            field=models.IntegerField(default=0),
        ),
    ]
