# Generated by Django 5.0.6 on 2024-07-13 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_account', '0004_alter_userprofile_faction'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField(default=0)),
                ('defender_intel', models.IntegerField(default=0)),
                ('defender_troops', models.IntegerField(default=0)),
                ('defender_technologies', models.IntegerField(default=0)),
                ('defender_bonus', models.IntegerField(default=0)),
                ('attacker_intel', models.IntegerField(default=0)),
                ('attacker_troops', models.IntegerField(default=0)),
                ('attacker_technologies', models.IntegerField(default=0)),
                ('attacker_bonus', models.IntegerField(default=0)),
                ('attacker_user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attacker_profile', to='user_account.userprofile')),
                ('defender_user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defender_profile', to='user_account.userprofile')),
            ],
        ),
    ]
