# Generated by Django 5.0.6 on 2024-07-14 11:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_intellog_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intellog',
            name='id',
        ),
        migrations.AddField(
            model_name='intellog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intellog',
            name='report_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
