# Generated by Django 5.0.6 on 2024-07-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_remove_intellog_id_intellog_date_intellog_report_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='intellog',
            name='attacker_elite_intel_troops_loss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='intellog',
            name='attacker_strong_intel_troops_loss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='intellog',
            name='attacker_weak_intel_troops_loss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='intellog',
            name='defender_attack_power',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='intellog',
            name='defender_defence_power',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='intellog',
            name='defender_elite_attack_troops',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='intellog',
            name='defender_elite_defence_troops',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='intellog',
            name='defender_elite_intel_troops',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='intellog',
            name='defender_elite_intel_troops_loss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='intellog',
            name='defender_income_power',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='intellog',
            name='defender_income_specialists',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='intellog',
            name='defender_intel_power',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='intellog',
            name='defender_strong_attack_troops',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='intellog',
            name='defender_strong_defence_troops',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='intellog',
            name='defender_strong_intel_troops',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='intellog',
            name='defender_strong_intel_troops_loss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='intellog',
            name='defender_untrained_units',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='intellog',
            name='defender_weak_attack_troops',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='intellog',
            name='defender_weak_defence_troops',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='intellog',
            name='defender_weak_intel_troops',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='intellog',
            name='defender_weak_intel_troops_loss',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='intellog',
            name='result',
            field=models.CharField(choices=[('Overwhelming Victory', 'Overwhelming Victory'), ('Clear Victory', 'Clear Victory'), ('Victory', 'Victory'), ('Loss', 'Loss'), ('Clear Loss', 'Clear Loss'), ('Overwhelming Loss', 'Overwhelming Loss')], max_length=20),
        ),
    ]
