# Generated by Django 5.0.6 on 2024-06-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_userprofile_account_name_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='faction',
            field=models.CharField(choices=[('amazons', 'Amazons'), ('spartans', 'Spartans'), ('atlantians', 'Atlantians'), ('witches', 'Witches')], default=2, max_length=20),
            preserve_default=False,
        ),
    ]
