# Generated by Django 5.0.6 on 2024-07-13 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_account', '0004_alter_userprofile_faction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Civilization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechnologyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_level', models.IntegerField(default=0)),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technology', to='user_account.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchableTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('cost', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('is_unique', models.BooleanField(default=False)),
                ('unique_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='technology.civilization')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technology.technologycategory')),
            ],
        ),
    ]
