# Generated by Django 5.0.6 on 2024-07-13 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0001_initial'),
        ('user_account', '0004_alter_userprofile_faction'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_completed', models.BooleanField(default=False)),
                ('research_points', models.IntegerField(default=0)),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technology.researchabletechnology')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technologies', to='user_account.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='Technology',
        ),
    ]
